name : "Build-Release"


on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main
        - master
#        - dev
#        - prod

job:
  build:
    name: Build-Release
    runs-on: macos-latest

    steps:
      - name: Chek repo
        uses: actions/checkout@v4

      - name: Setup JAVA JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17.0.12'
          cache: 'jdk'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64
          cache: 'true'

      - name: Setup Android Skd
        uses: android-actions/setup-android-sdk@v3

      - name: Get Flutter Packages Dep
        run: flutter pub get

      - name: Run generator builders
        run: flutter pub run_build_runner build --delete-conflicting-outputs

      - name: License Accpet
        run:  yes  | sdkmanager --license

      - name: Build Android APK
        run:  flutter build apk --release --obfuscate --split-debug-info=debug_info/ --tree-shake-icons --split-per-abi

      - name: Upload APK Github Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/apk/release/*.apk
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}



