name : "Build-Release"


on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main
        - master
#        - dev
#        - prod

jobs:
  build:
    name: Build-Release
    runs-on: macos-latest

    steps:
      - name: Chek repo
        uses: actions/checkout@v4

      - name: Setup JAVA JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17.0.12'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64
          cache: 'true'

      - name: Setup Android Skd
        uses: android-actions/setup-android@v3

      - name: Get Flutter Packages Dep
        run: flutter pub get

      - name: Run generator builders
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: License Accpet
        run:  yes  | sdkmanager --licenses

      - name: Build Android APK
        run:  flutter build apk --release --obfuscate --split-debug-info=debug_info/ --tree-shake-icons --split-per-abi

      - name: Upload APK Github Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/apk/release/*.apk
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}

      # iOS Build (Optional)
      - name: Build iOS (no code signing)
        run: flutter build ios --no-codesign
        continue-on-error: true

      - name: Package iOS .ipa
        run: |
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r app.ipa Payload
        continue-on-error: true

      - name: Upload iOS IPA Artifact to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/ios/iphoneos/app.ipa
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
        continue-on-error: true

      - name: Warn if iOS build failed
        if: failure()
        run: echo "::warning ::iOS build failed, continuing with Android release."
